import type { Metadata } from "next"

import StyledComponentsRegistry from "@/lib/registry"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Won Games",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
